import { createClient } from '@supabase/supabase-js'
import dotenv from 'zenv' // Custom env loader if needed, but let's assume process.env works or use dotenv

// Since I am in a CLI, I might need to load .env manually if not already loaded
// But typically tools load it.

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing Supabase credentials')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey)

async function verifySignupFlow() {
  const testEmail = `test_verify_${Date.now()}@example.com`
  const testPassword = 'TestPassword123!'
  
  console.log(`[test] Attempting signup for ${testEmail}...`)
  
  // 1. Trigger signup
  const { data: signupData, error: signupError } = await supabase.auth.signUp({
    email: testEmail,
    password: testPassword,
    options: {
      data: {
        role: 'parent_user',
        full_name: 'Test Verifier',
        username: `verifier_${Date.now()}`
      }
    }
  })

  if (signupError) {
    console.error('[test] Signup failed:', signupError.message)
    process.exit(1)
  }

  console.log('[test] Signup successful. User created:', signupData.user?.id)

  // 2. Generate confirmation link (Admin only)
  console.log('[test] Generating confirmation link...')
  const { data: linkData, error: linkError } = await supabase.auth.admin.generateLink({
    type: 'signup',
    email: testEmail,
    options: {
        redirectTo: 'http://localhost:3010/auth/confirm'
    }
  })

  if (linkError) {
    console.error('[test] Failed to generate link:', linkError.message)
    // Clean up
    await supabase.auth.admin.deleteUser(signupData.user!.id)
    process.exit(1)
  }

  const confirmationLink = linkData.properties.action_link
  console.log('[test] Confirmation link generated:', confirmationLink)

  // 3. Verify the link works by fetching it
  // We need to simulate the GET request that a user would trigger
  console.log('[test] Verifying link by fetching...')
  
  try {
    // We use the actual route in our app if possible, or just the Supabase link
    // The link generated by Supabase typically points to Supabase auth servers
    // which then redirect to our redirectTo URL.
    
    const response = await fetch(confirmationLink, { redirect: 'follow' })
    console.log('[test] Link fetch status:', response.status)
    console.log('[test] Final URL after redirects:', response.url)

    if (response.ok || response.status === 302 || response.status === 307 || response.url.includes('dashboard')) {
      console.log('[test] SUCCESS: Link works and redirects correctly.')
    } else {
      console.error('[test] FAILURE: Link might be broken or redirecting to error page.')
      process.exit(1)
    }
  } catch (err) {
    console.error('[test] Link verification failed with error:', err)
    process.exit(1)
  } finally {
    // Clean up
    console.log('[test] Cleaning up test user...')
    await supabase.auth.admin.deleteUser(signupData.user!.id)
  }
}

verifySignupFlow()
